### ISSUE TITLE
Offer Of Ideas

### ISSUE THREAD

**Issue by ColonolNutty** [lot51/core-library#7]
I'd love to offer some ideas if you would allow it. I've learned alot from my creation of the Sims 4 Community Library that I think would be very useful to you.

**Comment by ColonolNutty** [comment]
Please don't delete this issues. Now that the Deaderpool discord is dead and gone, I would like to finally salvage my reputation from their years of defamation.

**Comment by lot51** [comment]
There is nothing you could do to salvage your reputation. Your ideas are not welcome here.
